version: '3.5'
services:
  app:
    build:
      context: .
      dockerfile: versions/alpine3.23-php8.5/Dockerfile
  sut:
    image: alpine:3.12
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
